- CONTRIBUTING.md
- rfc3164.go
- rfc3164_test.go
Solution: We will use the [Collective Code Construction Contract](http://rfc.zeromq.org/spec:22) for our contributors policy.
> Problem: we have no contributors guide

- .travis.yml
Solution: add travis integration
> Problem: we do not have automated tests

- README.md
- rfc3164_test.go
Solution: add an example to the README, and a testable example to the unit tests.
> Problem: there were no usage examples

- rfc3164.go
> Problem: Parser did not need to be exported

- captainslog.go
- cmd/elauneind/main.go
- jsonforelastic.go
- jsonforelastic_test.go
- logger.go
- logger_test.go
- rfc3164.go
- rfc3164_test.go
Solution:  Add MostlyFeaturelessLogger. This is a mostly featureless logger that allows writing Err and Notice level syslog messages to a user configurable syslog facility.  It accepts a Fields type which raps a map of keys and values to be translated to JSON in the message.
> Problem: we want to produce structured logs without third party deps

- cmd/elauneind/main.go
> Problem: I want the default for elaneind to be LOCAL6 not LOCAL7

- README.md
Solution: Add some documentation
> Problem: the README was not helpful

- jsonkeymutator.go
- rfc3164_test.go
> Problem: we had questions about cee tag handling

- output_adapter.go
- output_channeler.go
Solution: name them correctly :)
> Problem: Brian named things wrong :)

- jsonkeytransformer_test.go
- tagrangetransformer.go
- tagrangetransformer_test.go
Adds a test for the reaper logic.
> Problem: reaper in tagrangetransformer was not tested

- README.md
- jsonkeytransformer_test.go
- parser_test.go
- syslogmsg.go
- tcp_outputter_test.go
Solution: add new captainslog.NewSyslogMsgFromBytes(b []byte) constructor.
> Problem: Creating SyslogMsg from bytes was cumbersome

- AUTHORS
> Problem: no AUTHORS file

- canal.go
- canal_test.go
- captainslog.go
- cmd/elauneind/main.go
- input_channeler.go
- output_channeler.go
- output_channeler_test.go
- tcp_inputter.go
* Add an InputChanneler to go along with the OutputChanneler.
* Add "Canal", which ties together an InputChanneler, multiple Transformers, and an OutputChanneler.
> Problem: creating a service with the library is too much work

- canal_test.go
- captainslog.go
- cmd/elauneind/main.go
- jsonkeytransformer.go
- jsonkeytransformer_test.go
- tagrangetransformer.go
- tagrangetransformer_test.go
This PR begins a refactor of the API to make it friendlier.
> Problem: our API was clumsy

- README.md
- examples_test.go
- jsonkeytransformer_test.go
- mutators_test.go
> Problem: we needed more examples

- timesincetransformer.go
- timesincetransformer_test.go
This PR reworks the timesincetransformer.
> Problem: want timesince in ms

- syslogmsg.go
- syslogmsg_test.go
Solution: add SyslogMsg.JSON() function that combines syslog headers and json content and returns json bytes.
> Problem: want to convert msg back to json

- parser_test.go
- priority_test.go
- syslogmsg_test.go
Moves tests to separate captainslog_test package for blackbox testing.
> Problem: want blackbox testing

- parser.go
- parser_test.go
- syslogmsg.go
- syslogmsg_test.go
- workdir/corpus/logwithpid.txt
Solution: modify parseTag() so that it can retrieve the separate components of the TAG field when the field includes the PID.
> Problem: we want to get pid and program name from tag

- parser.go
- parser_test.go
- syslogmsg_test.go
Solution: modify parseTag to ensure program only includes actual program name in all cases
> Problem: programname should not include colon from tag

- examples_test.go
- parser.go
- parser_test.go
- syslogmsg.go
Solution: rework the parsers for each section so that they can be called on their own by passing them a cursor position and a buffer.
WIP - don't merge yet :)
> Problem: want to use parser sections individually

- parser.go
> Problem: assigned offset but did not use it

- parser.go
- parser_test.go
- syslogmsg.go
Solution: move a bunch of tests to use  the subtest feature added in Go 1.7
> Problem: tests were hard to read and maintain

- parser.go
- parser_test.go
- priority.go
- syslogmsg.go
Solution: rework the pattern for object-to-string conversions.
> Problem: the syslogmsg builder does not convert to string properly

- priority.go
- priority_test.go
Solution: Add `FromString()` methods to both `Facility` and `Severity` types.
> Problem: We can't convert strings to Facility and Severity types

- README.md
Solution - let's update it! (work in progress).
> Problem: README is out of date

- syslogmsg.go
Solution: clean up style issues.
> Problem: SyslogMsg failed go vet

- parser.go
- parser_test.go
- priority_test.go
- syslogmsg_test.go
> Problem: we want code to be as clean as possible

- parser.go
- priority.go
Solution: do a little code cleanup.
> Problem: static checking found a few nitpicks

- parser_test.go
Verify IsJSON in the same way we already verify IsCee
> Add verification of IsJSON to all successful parse tests
