captainslog.go, jsonforelastic.go, jsonforelastic_test.go
Solution:
* Add a "mutator" interface that can be implemented for functions that wish to transform syslog messages.
* Implement a mutator that accepts rfc3164 @cee logs, scans their keys and changes all "." to "_".
=> Problem: elasticsearch 2.x does not accept periods in JSON fields

captainslog.go, jsonforelastic.go, jsonforelastic_test.go, rfc3164.go
Solution: change Mutator to return a copy of the original SyslogMsg instead of mutating the message in place.  In benchmarks, this actually turns out to be slightly faster than mutating the message in place, and it eliminates some complexity and potential errors when using this interface.
=> Problem: mutator should return mutated copy

jsonforelastic.go, rfc3164.go, rfc3164_test.go
Solution: Change the parser to save the @cee content as found as part of the syslog message.  This PR additionally collapses some "start / end" fields into the parser into tokenStart / tokenEnd as the specific fields were not needed.
=> Problem: cee parse impl. made reproducing log from struct difficult

rfc3164.go, rfc3164_test.go
Solution: add a String() method to SyslogMsg. Adding tests for this turned up a few issues with the time parsing - so this PR also fixes those issues.
=> Problem: we want to turn a SyslogMsg struct into a string

captainslog.go, cmd/elauneind/main.go, rfc3164.go, rfc3164_test.go
Solution: Add a minimal service that listens on TCP, parses incoming rfc3164 messages, extracts the JSON body (if found) and changes "."'s in JSON field names into something elasticsearch 2.x will accept.
=> Problem: I want a service that can fix json keys for elasticsearch

cmd/elauneind/main.go, output_gadget.go, output_gadget_tcp.go, output_gizmo.go, output_gizmo_test.go
This PR adds:
* OutputGizmo - "gizmos" are single units of functionality for doing things like receiving messages, sending messages, and modifying messages.
* OutputGadget - an interface for creating output gadgets - gadgets plug in to gizmos to provide functionality for the gizmo
This PR also modifies elauneind (our example and test service) to use an OutputGizmo with the TCP output gadget to forward syslog messages over TCP.
=> Problem: we would like an output plugin interface

jsonkeymutator.go, jsonkeymutator_test.go
Recursively iterate through incoming JSON documents, mutating all object keys as needed.
=> issue: elauneind does not support JSON of arbitrary depth

captainslog.go, tagrangetransformer.go, tagrangetransformer_test.go
Solution: add a new Mutator interface for mutating a *SyslogMsg, and TagArrayMutator, which is an implementation of Mutator that adds tag to a tag array.
=> Problem: we want to encapsulate the tagging logic into an interface

syslogmsg.go, syslogmsg_test.go
Now, if a SyslogMsg was originally not a @cee message, but then had JSONValues added to it's k/v map, when the message is serialized back to an rfc3164 message it will be converted to an @cee message.  The original SyslogMsg.Content is assigned to the "msg" key.
=> Problem: SyslogMsg.String() should include tags added after parse

jsonkeytransformer.go, jsonkeytransformer_test.go
Solution: use [Decoder.UseNumber](https://golang.org/pkg/encoding/json/#Decoder.UseNumber) to preserve the original representation.
Closes #29.
=> Problem: JSONKeyTransformer does not preserve numeric representation

jsonkeytransformer.go, parser.go
Solution: move code for maintaining numeric formatting to parser.go and modify JSONKeyTransformer to use the msg JSONValues map[string]interface{}.
=> Problem: JSONKeyTransfomer should use SyslogMsg.JSONValues

tcp_outputter_test.go
This PR increments the TCP port value in `TestTCPOutputter` to decrease potential conflicts when running tests
=> Problem: Port in TestTCPOutputter Causing Conflicts

.travis.yml, formatters.go, mutaterangetransformer_test.go, mutators.go, parser_test.go, syslogmsg.go, timesincetransformer.go, timesincetransformer_test.go
To solve a problem we needed the ability to tag logs with a duration since the last time a log that matched characteristics of that log line was seen.  The PR adds TimeSinceTransformer, a transformer which serves this purpose.
=> Problem: want to tag logs with durations

matchers.go, matchers_test.go
Since we do not currently distinguish between "program name" and "tag" when parsing, and since some programs include '[pid]' as part of the syslog tag, we need the TagMatcher to do a prefix match instead of an exact match until this is handled in SyslogMsg.
=> Problem: need to prefix match on program tag

.travis.yml, parser.go, parser_test.go, priority.go, syslogmsg.go, syslogmsg_test.go
Sometimes we want to parse "cee" rfc3164 messages without parsing the JSON in the message body. If we just want access to syslog headers, not parsing the JSON saves quite a bit of time. This PR adds an optional function argument ( "OptionDontParseJSON" ) that may be passed to the NewParser and NewSyslogMsg constructors to tell the parser to save "cee" message content without actually parsing it.
If JSON values are added to the message after the original parse, and SyslogMsg.String(), SyslogMsg.Bytes(), or SyslogMsg.JSON() are called, the message content will be parsed at that time in order to combine the fields within it with any fields added to SyslogMsg.JSONValues. Otherwise, SyslogMsg.Content will be used without ever incurring the penalty of a JSON parse.
This PR also fixes some minor …
=> Problem: sometimes dont want to parse json

parser.go, parser_test.go
When using a time format such as "2006-01-02T15:04:05.999999-07:00", in cases where a time's subseconds end in one or more 0s, time.Format(<format>) will truncate the length of the string.
This does not play well with code in the parser  that uses the length of time formats to find time strings within a syslog message: https://github.com/digitalocean/captainslog/blob/master/parser.go#L186-L201
This solution to the problem is not idea, but has the benefit of being simple, and in cases where the parser is dealing with syslog messages with standard time formats, does not add overhead.
Reference: https://github.com/digitalocean/captainslog/issues/50
=> Problem: go truncates time resolution when ending in 0s

parser.go, workdir/corpus/truncatedsubseconds.txt
Solution: add some logic for fast determination of rfc3339 style timestamps and a separate code path for handling them.
=> Problem: time parsing code was slow for non best cases

parser.go, parser_test.go
This PR adds support for finding JSON in the Content field of an RFC3164 message without requiring the @cee cookie in the message body. To stay efficient, if JSON parsing is enabled (OptionDontParseJSON was not passed to NewParser), ParseContent will perform a check to determine if the Content probably contains a JSON object.
=> Problem: want to suppot JSON without cee tag

syslogmsg.go, syslogmsg_test.go
Solution: add Set* methods to *captainslog.SyslogMsg to allow setting the components of a syslog message after a call to NewSyslogMsg.
=> Problem: we want to make syslog messages from scratch

parser.go, parser_test.go
Solution: harden up the  ParseTag function.
=> Problem: msgs with non alphanum at tag start could make it past parser

syslogmsg.go, syslogmsg_test.go
Rsyslog, listening on a local unix socket, expects a different logging format that what it receives on the wire (TCP/UDP). This PR adds formatting options for SyslogMsg.String() / SyslogMsg.Bytes() to support local logging format.
=> Problem: want to support logging to local syslog

syslogmsg.go, syslogmsg_test.go
This causes the `msg` field to be populated with the string representation of the Content, which may be JSON. If that Content contains a field labeled `msg`, it will be overwritten by the JSON string.
=> Problem: Building a SyslogMsg with SetContent does not set IsJSON flag if the message is JSON

README.md, parser.go, parser_test.go
Use the [tidwall/gjson](https://github.com/tidwall/gjson) JSON parser optionally.   Default behavior is unchanged.
For benchmarks with long lists of JSON fields this runs approx 3x faster.
=> Add Optional Faster Third Party JSON Parsing
